bin/app-upgrade: Removing unreachable code. Fixing it so it compares against the currently installed version instead of the last resolved version which makes it possible to retry installation of the same version. libexec/app-install-file: Allowing installation of the same file twice. Checks if the file has been unpacked earlier or not. Removes the unpacked version on failure.

diff --git a/libexec/app-install-file b/libexec/app-install-file
--- a/libexec/app-install-file
+++ b/libexec/app-install-file
@@ -48,21 +48,29 @@ then
   usage
 fi
 
-if [ -d versions/$version ]
+re="[.a-zA-Z0-9]"
+
+if [[ ! $version =~ $re ]]
 then
-  echo "Version $version is already installed"
-  exit 1
+  fatal "Invalid version: $version"
 fi
 
-mkdir -p versions/$version
-
-echo "Unpacking..."
-unzip -q -d versions/$version $file
-
-if [ ! -d versions/$version/root ]
+if [ -d versions/$version ]
 then
-  echo "Invalid zip file, did not contain a ./root directory." >&2
-  exit 1
+  echo "Version $version is already unpacked"
+else
+  mkdir -p versions/$version.tmp
+
+  echo "Unpacking..."
+  unzip -q -d versions/$version.tmp $file
+
+  if [ ! -d versions/$version.tmp/root ]
+  then
+    echo "Invalid zip file, did not contain a 'root' directory." >&2
+    rm -rf versions/$version.tmp
+    exit 1
+  fi
+  mv versions/$version.tmp versions/$version
 fi
 
 if [ -n "$prepend_config" ]
diff --git a/test/data/app-a/hooks/post-install b/test/data/app-a/hooks/post-install
--- a/test/data/app-a/hooks/post-install
+++ b/test/data/app-a/hooks/post-install
@@ -2,7 +2,13 @@
 
 set -u
 
-echo "Post install"
+echo "post-install"
+
+if [[ -e $APP_HOME/fail-post-install ]]
+then
+  echo "Simulating failure."
+  exit 1
+fi
 
 NAME=`basename $APP_HOME`
 
